require "json"

# package = JSON.parse(File.read(File.join(__dir__, "../../package.json")))
# version = package['dependencies']["doric"]
# version = version.gsub('^','').gsub('>=','')

source 'https://cdn.cocoapods.org/'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for TemplateLibrary
  pod 'DoricCore', :path => '../../../Doric'
  pod 'DoricDevkit', :path => '../../../Doric'
  
  pod 'SDWebImage'

  pod 'SDWebImageWebPCoder'

  pod 'PINCache'
  
  pod 'Dangle',           :path => '../../'
end
